### ISSUE TITLE
sources of webflow are not up to date

### ISSUE THREAD

**Issue by jtomekcz** [lime-company/powerauth-push-server#100]
Hello, sources on https://github.com/lime-company/powerauth-webflow/releases are not up to date. Sources in downloaded zip file are different then sources which there are cloned via git.

**Comment by petrdvorak** [comment]
What command do you use to clone soutces?

**Comment by jtomekcz** [comment]
git clone https://github.com/lime-company/powerauth-webflow.git powerauth-webflow (but problem is in case when i download sources as zip)

**Comment by romanstrobl** [comment]
The release zip is created from stable source code which is present in the `master` branch.

The default branch is `develop` after git clone. This branch is used for development and does not contain stable source code.

```
$ git clone https://github.com/lime-company/powerauth-webflow.git
Cloning into 'powerauth-webflow'...
remote: Counting objects: 15604, done.
remote: Compressing objects: 100% (179/179), done.
remote: Total 15604 (delta 61), reused 374 (delta 40), pack-reused 15160
Receiving objects: 100% (15604/15604), 2.85 MiB | 538.00 KiB/s, done.
Resolving deltas: 100% (4537/4537), done.
$ cd powerauth-webflow
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

nothing to commit, working tree clean
```

I believe this is the reason why sources differ between clone and zip. If you want to get the same sources, please compare the same branches and same commit (the zip contains source code frozen for the release at a particular commit).

**Comment by petrdvorak** [comment]
Already explained over the phone support.
