### ISSUE TITLE
Remove deprecated AsyncRestTemplate

### ISSUE THREAD

**Issue by petrdvorak** [lime-company/powerauth-push-server#106]
Spring Boot 2.0 deprecated `AsyncRestTemplate`, we should replace it with some updated mechanism.

**Comment by romanstrobl** [comment]
Hm, I missed this warning during compilation. I will look into it, the fix should be the same as in PA server.

**Comment by romanstrobl** [comment]
This issue is resolved by PR #119. `AsyncRestTemplate` was replaced by `WebClient`.
