### ISSUE TITLE
/push/service/status version

### ISSUE THREAD

**Issue by honzasmuk** [lime-company/powerauth-push-server#129]
It would be useful to get pushserver version in /push/service/status
```
{
    "status": "OK",
    "responseObject": {
        "applicationName": "powerauth-push",
        "applicationDisplayName": "PowerAuth 2.0 Push Server",
        "applicationEnvironment": "",
        "timestamp": "2018-06-19T05:58:26Z",
        "version": "0.18.0"
    }
}
```

**Comment by petrdvorak** [comment]
This is already implemented - we share version and build version. See this file for details.

https://github.com/lime-company/powerauth-push-server/blob/develop/powerauth-push-model/src/main/java/io/getlime/push/model/response/ServiceStatusResponse.java

The new version will be released on 2018/06/30...
