### ISSUE TITLE
Wrong method type in documentation

### ISSUE THREAD

**Issue by martintupy** [lime-company/powerauth-push-server#49]
Almost every method is assigned as `POST` type in detailed method explanation.
e.g.
![image](https://user-images.githubusercontent.com/30933614/31798314-2d7419d2-b533-11e7-8c1c-69145d4579fe.png)

**Comment by martintupy** [comment]
Fixed on my local wiki https://github.com/martintupy/powerauth-push-server/wiki/Push-Server-API. I don't have access to edit lime wiki.

**Comment by petrdvorak** [comment]
I will merge the changes. However, this endpoint: `/push/device/status/update` is `POST`.

```java
@RequestMapping(value = "status/update", method = RequestMethod.POST)
```

It must be `POST`, it can not be changed. It is called by PowerAuth Server in case activation status changes.

I will fix this one.
