### ISSUE TITLE
Push Credentials Setup - invalid iOS bundle ID

### ISSUE THREAD

**Issue by radekfrolik** [lime-company/powerauth-push-server#60]
When setting APNs Certificate attributes, Bundle ID with dash (-) character inside is not accepted. Error message is displayed instead: 'Please enter a valid iOS bundle ID (for example "io.getlime.app.MyApp")'

Screenshot:
<img width="1150" alt="apns" src="https://user-images.githubusercontent.com/25006124/33019135-6ddb862a-cdf9-11e7-9961-215185c361d7.png">

**Comment by petrdvorak** [comment]
The issue is caused by using the same regexp as for the Android package bundle, that does not allow '-' characters. We will relax the regexp a bit on iOS, to allow '-'....
