### ISSUE TITLE
Obsolete dependency in push server

### ISSUE THREAD

**Issue by romanstrobl** [lime-company/powerauth-push-server#66]
See screenshot:

![image](https://user-images.githubusercontent.com/26658588/33547571-bd03a0c0-d8e4-11e7-9f69-426ac17d9c75.png)

**Comment by petrdvorak** [comment]
Is this already fixed?

**Comment by martintupy** [comment]
Should be, see pull request 68

**Comment by petrdvorak** [comment]
... OK, then... close, maybe? :)
