### ISSUE TITLE
PushMessageSenderService#sendPushMessage gets stuck if not db connection pool is exhausted

### ISSUE THREAD

**Issue by honzasmuk** [lime-company/powerauth-push-server#96]
If multiple concurrent /push/message/send requests come the request threads may get stuck waiting at phaser.arriveAndAwaitAdvance() depending on db connection pool size and number of concurrent requests

Example: datasource pool maxActive=3, 4 concurrent requests. Each request thread gets db connection from pool when reading device registrations. Then PushMessageSenderService#sendPushMessage is called which starts async threads for sending one notification. When notification is sent callback is called and during the callback there is another db connection fetch because of push status saving:

`pushMessageDAO.save(pushMessageObject);`

Because this is running still in async thread (from the request thread) the JPA tries to fetch another connection from pool. This fails after 30s (maxWaitTime).

But there is no try/catch/finaly in the callback code. Therefore the `phaser.arriveAndDeregister();` is never called and the request thread is stuck forever along with db connection.

There should be better exception handling regarding phaser callbacks. Also some recommendation about db connection pool size vs request thread pool size - one request eats two db connections => there should be minimum 2x more db connections in pool then max number of  http request handler threads.

**Comment by petrdvorak** [comment]
We have already made some improvements here, they are waiting for code review by @romanstrobl, you can add yours if needed:

lime-company/powerauth-push-server#94

Newly, we:

1) Do cleanup in `finally`
2) Log the issue as severe.
